---
debug: true
contextTimeout: 5

server:
  address: ":8080"

database:
  driver: "mysql"
  host: "192.168.100.202"
  port: 3306
  username: "root"
  password: "Wf3364m!"
  name: "go_starter"

nsq:
  host: "192.168.100.202"
  port: 4150
...